language: python

python:
  - 3.6

services:
  - postgresql

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - python manage.py migrate --noinput
  - python manage.py collectstatic --noinput

script:
  - coverage run --source='main' manage.py test --verbosity 2
  - coverage report -m

after_success:
  - echo "success"
  - coveralls
